# Generated by Django 3.2.7 on 2021-09-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bncomment',
            old_name='name',
            new_name='bnipplename',
        ),
        migrations.RenameField(
            model_name='bottlecomment',
            old_name='name',
            new_name='bottlename',
        ),
        migrations.RenameField(
            model_name='diapercomment',
            old_name='name',
            new_name='diapername',
        ),
    ]
